services:
  financemanager:
    image: ${DOCKER_REGISTRY-}financemanager
    build:
      context: .
      dockerfile: FinanceManager/Dockerfile
    environment: 
      - ConnectionStrings:DefaultConnection=${CONNECTIONSTRING}
    networks:
      - finance-network
  
  db:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: finance_manager_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - finance-network
  
  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 80:8080
      - 443:8080
    networks:
      - finance-network

networks:
  finance-network:
    driver: bridge

volumes:
  postgres-data: